"""empty message

Revision ID: 88ecee930abf
Revises: 
Create Date: 2025-05-31 14:20:17.930520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ecee930abf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('mother_last_name', sa.String(length=60), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'PROFESSIONAL', 'STUDENT', 'PATIENT', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('education_level', sa.Enum('NONE', 'PRIMARY', 'SECONDARY', 'HIGH_SCHOOL', 'TECHNICAL', 'PROFESSIONAL', 'POSTGRADUATE', name='educationlevel'), nullable=True),
    sa.Column('education_area', sa.String(length=120), nullable=True),
    sa.Column('institution', sa.String(length=120), nullable=True),
    sa.Column('registration_number', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('professional_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('medical_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('EMPTY', 'IN_PROGRESS', 'IN_REVIEW', 'FEEDBACK', 'APPROVED', 'CORRECTION_REQUESTED', 'CONFIRMED', name='filestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_trails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_file_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('performed_by', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['medical_file_id'], ['medical_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_file_id', sa.Integer(), nullable=False),
    sa.Column('hypertension', sa.Text(), nullable=True),
    sa.Column('diabetes', sa.Text(), nullable=True),
    sa.Column('cancer', sa.Text(), nullable=True),
    sa.Column('heart_disease', sa.Text(), nullable=True),
    sa.Column('kidney_disease', sa.Text(), nullable=True),
    sa.Column('liver_disease', sa.Text(), nullable=True),
    sa.Column('mental_illness', sa.Text(), nullable=True),
    sa.Column('congenital_malformations', sa.Text(), nullable=True),
    sa.Column('others', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medical_file_id'], ['medical_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gynecological_background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_file_id', sa.Integer(), nullable=False),
    sa.Column('not_applicable', sa.Boolean(), nullable=False),
    sa.Column('menarche', sa.String(length=20), nullable=True),
    sa.Column('cycle', sa.String(length=60), nullable=True),
    sa.Column('pregnancies', sa.Integer(), nullable=True),
    sa.Column('births', sa.Integer(), nullable=True),
    sa.Column('abortions', sa.Integer(), nullable=True),
    sa.Column('last_menstruation', sa.String(length=30), nullable=True),
    sa.Column('last_pap', sa.String(length=30), nullable=True),
    sa.Column('contraceptive_method', sa.String(length=120), nullable=True),
    sa.Column('others', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medical_file_id'], ['medical_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('non_pathological_background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_file_id', sa.Integer(), nullable=False),
    sa.Column('education_level', sa.String(length=60), nullable=True),
    sa.Column('economic_activity', sa.String(length=120), nullable=True),
    sa.Column('housing_type', sa.String(length=60), nullable=True),
    sa.Column('services', sa.Text(), nullable=True),
    sa.Column('lifestyle', sa.Text(), nullable=True),
    sa.Column('nutrition', sa.Text(), nullable=True),
    sa.Column('habits', sa.Text(), nullable=True),
    sa.Column('physical_activity', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medical_file_id'], ['medical_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pathological_background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_file_id', sa.Integer(), nullable=False),
    sa.Column('personal_diseases', sa.Text(), nullable=True),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('hospitalizations', sa.Text(), nullable=True),
    sa.Column('surgeries', sa.Text(), nullable=True),
    sa.Column('traumatisms', sa.Text(), nullable=True),
    sa.Column('transfusions', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('others', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medical_file_id'], ['medical_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_file_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['medical_file_id'], ['medical_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_data')
    op.drop_table('pathological_background')
    op.drop_table('non_pathological_background')
    op.drop_table('gynecological_background')
    op.drop_table('family_background')
    op.drop_table('audit_trails')
    op.drop_table('medical_files')
    op.drop_table('student_profiles')
    op.drop_table('professional_profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
